   stages:
   - build
   - deploy
   
   build:
     stage: build
     image: node:latest
     script:
     - npm install
     - ng build --prod
     artifacts:
       paths:
       - dist/
   
   deploy:
     stage: deploy
     image: python:latest
     before_script:
     - pip install awscli
     script:
     - aws s3 cp dist/ s3://$S3_BUCKET_NAME/ --recursive
     after_script:
     - rm -r dist
